# Generated by Django 5.0.1 on 2024-01-14 15:17

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0002_alter_product_is_active"),
    ]

    operations = [
        migrations.AddField(
            model_name="category",
            name="name",
            field=models.CharField(default=".", max_length=255),
        ),
    ]
